# Generated by Django 3.2.6 on 2021-09-18 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('product_price', models.FloatField()),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(upload_to='')),
                ('product_brand', models.CharField(max_length=500)),
                ('product_color', models.CharField(max_length=50)),
                ('product_companyName', models.CharField(max_length=500)),
                ('product_total_stock', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypbackendapi.category')),
            ],
        ),
    ]
