# Generated by Django 3.2.6 on 2021-11-18 07:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_password', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=230)),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_registerDate', models.DateTimeField()),
                ('customer_image', models.ImageField(upload_to='uploads/images')),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_name', models.CharField(max_length=150)),
                ('shipper_email', models.EmailField(max_length=100)),
                ('shipper_image', models.ImageField(upload_to='uploads/images')),
                ('shipper_phone_no', models.CharField(max_length=20)),
                ('shipper_address', models.CharField(max_length=200)),
                ('shipper_Regiter_Date', models.DateField()),
                ('shipper_verified', models.BooleanField()),
                ('shipper_detail', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=150)),
                ('offer_Finish_Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategory_name', models.CharField(max_length=500)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fypbackendapi.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('product_price', models.FloatField()),
                ('product_description', ckeditor.fields.RichTextField()),
                ('product_brand', models.CharField(max_length=500)),
                ('product_color', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to='uploads/images')),
                ('product_companyName', models.CharField(max_length=500)),
                ('product_total_stock', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypbackendapi.category')),
                ('subCategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fypbackendapi.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedReview',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='fypbackendapi.product')),
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fypbackendapi.customer')),
                ('rating', models.FloatField()),
                ('Customer_Id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cus_id', to='fypbackendapi.customer')),
                ('Product_Id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pro_id', to='fypbackendapi.product')),
            ],
            bases=('fypbackendapi.customer', 'fypbackendapi.product', models.Model),
        ),
    ]
