# Generated by Django 3.2.6 on 2021-11-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackendapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_address',
        ),
    ]
