# Generated by Django 3.2.6 on 2021-12-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackendapi', '0002_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_password',
            field=models.CharField(default='', max_length=100000000000),
        ),
    ]
