# Generated by Django 3.2.6 on 2021-10-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackendapi', '0005_alter_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150)),
                ('event_days', models.IntegerField()),
                ('event_hours', models.IntegerField()),
                ('event_minutes', models.IntegerField()),
                ('event_seconds', models.IntegerField()),
            ],
        ),
    ]
