# Generated by Django 3.2.6 on 2021-10-10 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackendapi', '0006_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_days',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_hours',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_minutes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_seconds',
        ),
        migrations.AddField(
            model_name='event',
            name='event_Finish_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
