# Generated by Django 3.2.6 on 2021-10-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackendapi', '0007_auto_20211010_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_Finish_Time',
            field=models.DateField(),
        ),
    ]
