# Generated by Django 3.2.6 on 2021-10-10 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackendapi', '0009_remove_event_event_finish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_Finish_Time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
