# Generated by Django 3.2.6 on 2021-10-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackendapi', '0010_event_event_finish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_Finish_Time',
            field=models.DateTimeField(),
        ),
    ]
