# Generated by Django 3.2.6 on 2021-10-27 02:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackendapi', '0012_shipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='shipper_detail',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
