# Generated by Django 3.2.6 on 2021-10-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackendapi', '0013_shipper_shipper_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
