# Generated by Django 3.2.6 on 2021-10-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackendapi', '0016_auto_20211031_0446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
