# Generated by Django 3.2.6 on 2021-10-31 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackendapi', '0017_rename_productimages_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_name',
            field=models.CharField(max_length=200),
        ),
    ]
