# Generated by Django 3.2.6 on 2021-10-31 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackendapi', '0019_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/images'),
            preserve_default=False,
        ),
    ]
