# Generated by Django 3.2.6 on 2021-10-31 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackendapi', '0020_product_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
