# Generated by Django 3.2.6 on 2021-11-11 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fypbackendapi', '0021_delete_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=150)),
                ('person_email', models.EmailField(max_length=230)),
                ('person_address', models.CharField(max_length=200)),
                ('person_registerDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fypbackendapi.person')),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_password', models.CharField(max_length=30)),
                ('customer_phone_image', models.ImageField(upload_to='uploads/images')),
            ],
            bases=('fypbackendapi.person', models.Model),
        ),
        migrations.CreateModel(
            name='SubmittedReview',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='fypbackendapi.product')),
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fypbackendapi.customer')),
                ('rating', models.FloatField()),
                ('Customer_Id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cus_id', to='fypbackendapi.customer')),
                ('Product_Id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pro_id', to='fypbackendapi.product')),
            ],
            bases=('fypbackendapi.customer', 'fypbackendapi.product', models.Model),
        ),
    ]
